ALTER TABLE orders
ADD COLUMN IF NOT EXISTS tax_inclusive BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS bill_discount_type TEXT NOT NULL DEFAULT 'amount'
  CHECK (bill_discount_type IN ('amount', 'percent')),
ADD COLUMN IF NOT EXISTS bill_discount_value NUMERIC(14,2) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS split_from_order_id UUID NULL REFERENCES orders(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS merged_into_order_id UUID NULL REFERENCES orders(id) ON DELETE SET NULL;

ALTER TABLE order_items
ADD COLUMN IF NOT EXISTS discount_type TEXT NOT NULL DEFAULT 'amount'
  CHECK (discount_type IN ('amount', 'percent')),
ADD COLUMN IF NOT EXISTS tax_inclusive BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS pre_tax_amount NUMERIC(14,2) NOT NULL DEFAULT 0;

ALTER TABLE invoice_items
ADD COLUMN IF NOT EXISTS discount_type TEXT NOT NULL DEFAULT 'amount'
  CHECK (discount_type IN ('amount', 'percent')),
ADD COLUMN IF NOT EXISTS tax_inclusive BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS pre_tax_amount NUMERIC(14,2) NOT NULL DEFAULT 0;

ALTER TABLE invoices
ADD COLUMN IF NOT EXISTS round_off NUMERIC(14,2) NOT NULL DEFAULT 0;
